
x-airflow-common: &airflow-common
  image: apache/airflow:2.8.1-python3.10
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/key.json
    GCP_PROJECT_ID: ${GCP_PROJECT_ID}
    GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
  env_file:
    - .env
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./pipeline:/opt/airflow/pipeline
    - ./ingestion:/opt/airflow/ingestion
    - ./key.json:/opt/airflow/key.json
  depends_on:
    postgres:
      condition: service_healthy

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    restart: on-failure

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  spark:
    image: apache/spark:3.5.1
    entrypoint: /opt/spark/bin/spark-class
    command: org.apache.spark.deploy.master.Master
    environment:
      - SPARK_NO_DAEMONIZE=true
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark/work-dir/key.json
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./spark:/opt/spark/work-dir/jobs
      - ./key.json:/opt/spark/work-dir/key.json

volumes:
  postgres_data: